# Two Dimensional Numpy


In [1]:
#import 
import numpy as np

In [2]:
a=[ [11,12,13], [21,22,23] ,[31,32,33] ]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [4]:
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
A.ndim

2

In [6]:
A.size

9

In [7]:
A.shape

(3, 3)

In [8]:
A.size

9

In [10]:
A[0][0]

11

In [11]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [12]:
A[0,0:2]

array([11, 12])

In [13]:
A[0:2,2]

array([13, 23])

In [15]:

x=np.array( [  [1,0],  [0,1]  ] )
y=np.array(  [  [2,1] , [1,2]      ]    )
x,y

(array([[1, 0],
        [0, 1]]),
 array([[2, 1],
        [1, 2]]))

In [16]:
x+y

array([[3, 1],
       [1, 3]])

In [17]:
y

array([[2, 1],
       [1, 2]])

In [18]:
y*2

array([[4, 2],
       [2, 4]])

In [19]:

x=np.array( [  [1,0],  [0,1]  ] )
y=np.array(  [  [2,1] , [1,2]      ]    )
x,y

(array([[1, 0],
        [0, 1]]),
 array([[2, 1],
        [1, 2]]))

In [20]:
x*y

array([[2, 0],
       [0, 2]])

In [23]:
a=np.array( [  [0,1,1],[1,0,1] ]  )
b=np.array(  [ [1,1] ,[1,1] ,[-1,1] ]       )

In [24]:
a,b

(array([[0, 1, 1],
        [1, 0, 1]]),
 array([[ 1,  1],
        [ 1,  1],
        [-1,  1]]))

In [25]:
np.dot(a,b)

array([[0, 2],
       [0, 2]])

In [28]:

X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
X,Y

(array([[1, 0],
        [0, 1]]),
 array([[2, 2],
        [2, 2]]))

In [29]:
Z

array([[2, 2],
       [2, 2]])